remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Recipes Throughout Years]
description: [This website detailes Exploratory Data Analysis and Visualizations on the Recipes Dataset]