remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: [Recipes Throughout Years]
description: [This website detailes Exploratory Data Analysis and Visualizations on the Recipes Dataset]